data:
  train_files: hiyouga/math12k@train
  val_files: 
  - hiyouga/math12k@test
  prompt_key: problem
  answer_key: answer
  image_key: images
  video_key: videos
  image_dir: null
  video_fps: 2.0
  max_prompt_length: 2048
  max_response_length: 4096
  rollout_batch_size: 512  # equivalent to verl's data.train_batch_size
  mini_rollout_batch_size: null  # equivalent to verl's data.gen_batch_size
  val_batch_size: 1024
  format_prompt: ./examples/format_prompt/reasoning.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  max_pixels: 1003520 # 1280*28*28
  min_pixels: 200704 # 256*28*28
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2
  concat_responses: false
  online_filtering: false  # dapo filter groups
  filter_key: overall
  filter_low: 0.01
  filter_high: 0.99

worker:
  actor:
    global_batch_size: 128  # equivalent to verl's actor.ppo_mini_batch_size
    micro_batch_size_per_device_for_update: 4  # equivalent to verl's actor.ppo_micro_batch_size_per_gpu
    micro_batch_size_per_device_for_experience: 16  # equivalent to verl's rollout.log_prob_micro_batch_size_per_gpu
    max_grad_norm: 1.0
    padding_free: true
    dynamic_batching: true
    ulysses_size: 1
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 5.0e-7
      weight_decay: 1.0e-2
      strategy: adamw_bf16 # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      torch_dtype: bf16 # here: for bf16
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 4
    temperature: 1.0
    top_p: 1.0
    limit_images: 0
    gpu_memory_utilization: 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    disable_tqdm: false
    training_stage: 1
    val_override_config:
      temperature: 0.6
      top_p: 0.95
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: selective_batch
    reward_function: ./examples/reward_function/self_correction.py:compute_score
    val_reward_function: ./examples/reward_function/math.py:compute_score

trainer:
  total_epochs: 15
  max_steps: null
  project_name: easy_r1
  experiment_name: qwen2_5_7b_math_grpo
  logger: ["file", "wandb"]
  nnodes: 1
  n_gpus_per_node: 8
  max_try_make_batch: 20  # -1 means no limit
  val_freq: 5  # -1 to disable
  val_before_train: true
  val_only: false
  val_generations_to_log: 3
  save_freq: 5  # -1 to disable
  save_limit: 30  # -1 to disable
  save_model_only: false
  save_metric: reward  # reward | accuracy_original | accuracy_sampled
  save_topk_best: 10  # protect top-3 avg accuracy checkpoints
  save_checkpoint_path: null
  load_checkpoint_path: null
  find_last_checkpoint: true
